server:
  servlet:
    context-path: /api

spring:
  application:
    name: hr-system

  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5432/hr_db
    username: postgres
    password: secret

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true